insert into brands (logo, name)
values
    ("Allen-Solly.png", "Allen Solly"),
    ("UCB.png", "UCB"),
    ("Killer.png", "Killer"),
    ("Levis.jpg", "Levis"),
    ("Jockey.png", "Jockey"),
    ("Penguin.jpg", "Penguin"),
    ("Pearson.png","Pearson"),
    ("Harper-Collins.png", "Harper-Collions"),
    ("Voltas.png","Voltas"),
    ("Godrej.png","Godrej"),
    ("Haier.png","Haier"),
    ("Whirlpool.png","Whirlpool"),
    ("Nivia_Sports_official_logo","Nivia Sports"),
    ("Vector_X.jpg","Vector"),
    ("Spartan.png","Spartan"),
    ("SG.jpg","SG"),
    ("Konex.png","Konex"),
    ("Jagger-Smith.jpg","Jagger Smith"),
    ("Yonex.png","Yonex"),
    ("MSI.jpg","MSI"),
    ("apple.png","apple"),
    ("Canon.png", "Canon"),
    ("Samsung.png","Samsung"),
    ("HP.png","HP"),
    ("Beardo.jpeg","Beardo"),
    ("Philips.png","Philips"),
    ("oppo.jpg","Oppo"),
    ("google-pixel.png","Google Pixel"),
    ("Oneplus.jpg","One Plus")